let age = 15;
console.log( age);
let Name = 'Sofia';
console.log( Name);
let isStudent = true;
console.log(isStudent);
const MY_STRING = 'Common sense ? I do not remember having such an useless thing';
console.log(MY_STRING);
let myNumber = 34;
console.log( myNumber + 10);
let myNull = null;
console.log(myNull);
let userName = prompt('please enter your name');
console.log(userName);
let enteredName = 'misa';
alert(`welcome ${enteredName}`);
let message = confirm('please confirm');
alert('Dangerous');
let warning = confirm('please confirm');
